services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text-extraction-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn --env-file .env app.main:app --host 0.0.0.0 --port 8000 --reload
